-- =====================================================
-- Migration 012: Add Team Member Reports Table
-- =====================================================
-- This migration adds a table to cache AI-generated
-- team member performance reports for 24 hours
-- =====================================================

-- Create team_member_reports table
CREATE TABLE IF NOT EXISTS team_member_reports (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  organization_id UUID NOT NULL,
  user_id UUID NOT NULL, -- The team member being reported on
  generated_by UUID NOT NULL, -- The lead who generated the report
  report_markdown TEXT NOT NULL, -- Full markdown report from LLM
  
  -- Metadata about the report generation
  start_date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  -- Metrics snapshot (for quick display without parsing markdown)
  metrics_snapshot JSONB DEFAULT '{}'::JSONB,
  
  -- Cache expiry (24 hours from generation)
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '24 hours'),
  
  CONSTRAINT fk_organization
    FOREIGN KEY (organization_id)
    REFERENCES organizations(id)
    ON DELETE CASCADE,
  
  CONSTRAINT fk_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE,
  
  CONSTRAINT fk_generated_by
    FOREIGN KEY (generated_by)
    REFERENCES users(id)
    ON DELETE SET NULL
);

-- Comments
COMMENT ON TABLE team_member_reports IS 'Caches AI-generated team member performance reports for 24 hours';
COMMENT ON COLUMN team_member_reports.report_markdown IS 'Full markdown report generated by Google Gemini LLM';
COMMENT ON COLUMN team_member_reports.metrics_snapshot IS 'JSON snapshot of key metrics for quick display';
COMMENT ON COLUMN team_member_reports.expires_at IS 'Cache expiry time (24 hours from generation)';

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_team_reports_org ON team_member_reports(organization_id);
CREATE INDEX IF NOT EXISTS idx_team_reports_user ON team_member_reports(user_id);
CREATE INDEX IF NOT EXISTS idx_team_reports_expires ON team_member_reports(expires_at);
CREATE INDEX IF NOT EXISTS idx_team_reports_lookup ON team_member_reports(organization_id, user_id, expires_at);

-- =====================================================
-- Enable Row-Level Security
-- =====================================================
ALTER TABLE team_member_reports ENABLE ROW LEVEL SECURITY;

-- Policy: Organization leads can view reports for their organization
CREATE POLICY "Leads can view org reports"
ON team_member_reports FOR SELECT
TO authenticated
USING (
  organization_id = public.user_organization_id()
  AND (SELECT role FROM public.users WHERE id = auth.uid()) = 'lead'
);

-- Policy: Organization leads can insert reports for their organization
CREATE POLICY "Leads can generate reports"
ON team_member_reports FOR INSERT
TO authenticated
WITH CHECK (
  organization_id = public.user_organization_id()
  AND (SELECT role FROM public.users WHERE id = auth.uid()) = 'lead'
  AND generated_by = auth.uid()
);

-- Policy: Clean up expired reports (allow deletion by anyone authenticated)
CREATE POLICY "Allow cleanup of expired reports"
ON team_member_reports FOR DELETE
TO authenticated
USING (expires_at < NOW());

-- =====================================================
-- Cleanup Function (Optional)
-- =====================================================
-- Function to automatically clean up expired reports
CREATE OR REPLACE FUNCTION cleanup_expired_reports()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  DELETE FROM team_member_reports
  WHERE expires_at < NOW();
END;
$$;

COMMENT ON FUNCTION cleanup_expired_reports IS 'Removes expired team member reports from cache';

-- =====================================================
-- Verification
-- =====================================================
DO $$
BEGIN
  RAISE NOTICE '=== Migration 012 Complete ===';
  RAISE NOTICE 'Created team_member_reports table';
  RAISE NOTICE 'Added RLS policies for organization leads';
  RAISE NOTICE 'Added cleanup function for expired reports';
END $$;
