/**
 * Report Generator Service
 * Generates PDF reports using PDFKit
 */

import PDFDocument from 'pdfkit';
import { Readable } from 'stream';
import { ReportData } from '../types/report-types';

export class ReportGenerator {
  /**
   * Generate PDF report and return as stream
   */
  generatePDF(reportData: ReportData): Readable {
    const doc = new PDFDocument({ margin: 50 });

    // Header
    this.addHeader(doc, reportData);

    // Metadata Section
    this.addMetadataSection(doc, reportData);

    // Executive Summary (Metrics)
    this.addExecutiveSummary(doc, reportData);

    // Decisions Section
    this.addDecisionsSection(doc, reportData);

    // Assumptions Section
    this.addAssumptionsSection(doc, reportData);

    // Constraints Section
    this.addConstraintsSection(doc, reportData);

    // Footer
    this.addFooter(doc, reportData);

    doc.end();
    return doc;
  }

  private addHeader(doc: PDFKit.PDFDocument, reportData: ReportData) {
    doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .text('DECIVUE Activity Report', { align: 'center' })
      .moveDown(0.5)
      .fontSize(12)
      .font('Helvetica')
      .text(reportData.metadata.organizationName, { align: 'center' })
      .moveDown(2);
  }

  private addMetadataSection(doc: PDFKit.PDFDocument, reportData: ReportData) {
    const { metadata } = reportData;

    doc
      .fontSize(10)
      .font('Helvetica')
      .text(`Report Type: ${metadata.reportType === 'individual' ? 'Individual Activity' : 'Organization-Wide'}`)
      .text(`Generated By: ${metadata.generatedBy.fullName} (${metadata.generatedBy.email})`)
      .text(`Role: ${metadata.generatedBy.role}`)
      .text(`Generated At: ${metadata.generatedAt.toLocaleString()}`)
      .moveDown(2);

    if (metadata.dateRange) {
      doc
        .text(`Date Range: ${metadata.dateRange.start.toLocaleDateString()} - ${metadata.dateRange.end.toLocaleDateString()}`)
        .moveDown(2);
    }
  }

  private addExecutiveSummary(doc: PDFKit.PDFDocument, reportData: ReportData) {
    doc
      .fontSize(16)
      .font('Helvetica-Bold')
      .text('Executive Summary', { underline: true })
      .moveDown(0.5);

    const { metrics } = reportData;

    doc
      .fontSize(10)
      .font('Helvetica')
      .text(`Total Decisions: ${metrics.totalDecisions}`)
      .text(`Average Decision Age: ${metrics.averageDecisionAge} days`)
      .text(`Recent Review Rate: ${metrics.recentReviewRate}%`)
      .moveDown(1);

    // Lifecycle Distribution
    doc
      .fontSize(12)
      .font('Helvetica-Bold')
      .text('Lifecycle Distribution:')
      .fontSize(10)
      .font('Helvetica')
      .text(`  • STABLE: ${metrics.lifecycleDistribution.STABLE}`)
      .text(`  • UNDER REVIEW: ${metrics.lifecycleDistribution.UNDER_REVIEW}`)
      .text(`  • AT RISK: ${metrics.lifecycleDistribution.AT_RISK}`)
      .text(`  • INVALIDATED: ${metrics.lifecycleDistribution.INVALIDATED}`)
      .text(`  • RETIRED: ${metrics.lifecycleDistribution.RETIRED}`)
      .moveDown(1);

    // Assumption Status Distribution
    doc
      .fontSize(12)
      .font('Helvetica-Bold')
      .text('Assumption Status Distribution:')
      .fontSize(10)
      .font('Helvetica')
      .text(`  • VALID: ${metrics.assumptionStatusDistribution.VALID}`)
      .text(`  • SHAKY: ${metrics.assumptionStatusDistribution.SHAKY}`)
      .text(`  • BROKEN: ${metrics.assumptionStatusDistribution.BROKEN}`)
      .moveDown(2);
  }

  private addDecisionsSection(doc: PDFKit.PDFDocument, reportData: ReportData) {
    doc.addPage();

    doc
      .fontSize(16)
      .font('Helvetica-Bold')
      .text('Decisions', { underline: true })
      .moveDown(1);

    if (reportData.decisions.length === 0) {
      doc
        .fontSize(10)
        .font('Helvetica-Oblique')
        .text('No decisions found.')
        .moveDown(2);
      return;
    }

    reportData.decisions.forEach((decision, index) => {
      // Add page break if needed
      if (doc.y > 650) {
        doc.addPage();
      }

      doc
        .fontSize(12)
        .font('Helvetica-Bold')
        .text(`${index + 1}. ${decision.title}`)
        .fontSize(10)
        .font('Helvetica')
        .text(`   Lifecycle: ${decision.lifecycle}`, { indent: 10 })
        .text(`   Created: ${decision.createdAt.toLocaleDateString()} by ${decision.creatorName}`, { indent: 10 })
        .text(`   Last Reviewed: ${decision.lastReviewedAt.toLocaleDateString()}`, { indent: 10 })
        .text(`   Assumptions: ${decision.assumptionCount} | Constraints: ${decision.constraintCount}`, { indent: 10 })
        .text(`   Description: ${decision.description.substring(0, 200)}${decision.description.length > 200 ? '...' : ''}`, { indent: 10 })
        .moveDown(1);
    });
  }

  private addAssumptionsSection(doc: PDFKit.PDFDocument, reportData: ReportData) {
    doc.addPage();

    doc
      .fontSize(16)
      .font('Helvetica-Bold')
      .text('Assumptions', { underline: true })
      .moveDown(1);

    if (reportData.assumptions.length === 0) {
      doc
        .fontSize(10)
        .font('Helvetica-Oblique')
        .text('No assumptions found.')
        .moveDown(2);
      return;
    }

    reportData.assumptions.forEach((assumption, index) => {
      if (doc.y > 650) {
        doc.addPage();
      }

      doc
        .fontSize(10)
        .font('Helvetica')
        .text(`${index + 1}. ${assumption.description}`)
        .text(`   Status: ${assumption.status}`, { indent: 10 })
        .text(`   Created: ${assumption.createdAt.toLocaleDateString()}`, { indent: 10 })
        .moveDown(0.5);
    });
  }

  private addConstraintsSection(doc: PDFKit.PDFDocument, reportData: ReportData) {
    doc.addPage();

    doc
      .fontSize(16)
      .font('Helvetica-Bold')
      .text('Constraints', { underline: true })
      .moveDown(1);

    if (reportData.constraints.length === 0) {
      doc
        .fontSize(10)
        .font('Helvetica-Oblique')
        .text('No constraints found.')
        .moveDown(2);
      return;
    }

    reportData.constraints.forEach((constraint, index) => {
      if (doc.y > 650) {
        doc.addPage();
      }

      doc
        .fontSize(10)
        .font('Helvetica')
        .text(`${index + 1}. ${constraint.name}`)
        .text(`   Type: ${constraint.constraintType}`, { indent: 10 })
        .text(`   Description: ${constraint.description}`, { indent: 10 })
        .moveDown(0.5);
    });
  }

  private addFooter(doc: PDFKit.PDFDocument, reportData: ReportData) {
    const pageCount = doc.bufferedPageRange().count;

    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i);
      doc
        .fontSize(8)
        .font('Helvetica')
        .text(
          `Generated by DECIVUE | ${reportData.metadata.generatedAt.toLocaleString()} | Page ${i + 1} of ${pageCount}`,
          50,
          doc.page.height - 50,
          { align: 'center', width: doc.page.width - 100 }
        );
    }
  }
}
